version: '3'
services:
  localstack-test:
    image: localstack/localstack:0.11.3
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-west-2
      - PORT_WEB_UI=8090
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - './.localstack0.11.2:/tmp/localstack'
  test-service:
    depends_on:
      - localstack-test
    build:
      context: ./test-service
    restart: always
    volumes:
      - './test-service:/usr/src/app/test-service:delegated'
    command: |
      sh -c "dockerize -wait http://localstack-test:4566/health -timeout 60s -wait-retry-interval 10s \
      sh /usr/src/app/test-service/docker-entrypoint.sh && tail -f /dev/null"
